name: cache-dependencies
on: push

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                python-version: [3.9, 3.10]

        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: set-up python
              uses: actions/setup-python@v7
              with:
                python-version: ${{ matrix.python-version }}

            - name: cache pip dependencies
              uses: actions/cache@v6
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**requirements.txt') }}

            - name: install dependencies
              run: pip install -r cache-dependencies/requirements.txt

            - name: run tests
              run: pytest test_app.py
