name: containers job
on:
    workflow_dispatch:

jobs:
    job1:
        runs-on: ubuntu-latest
        container:
            image: ubuntu:22.04

        steps:
            - name: check os name
              run: cat /etc/os-release
            
            - name: print the message
              run: echo $whoami