name: docker push
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: build
              run: docker build -t mdfaiz01/sample-image:test -f docker/Dockerfile .

            - name: run container
              run: docker run --rm mdfaiz01/sample-image:test echo "Container is alive!"


    docker:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: login to docker hub
              uses: docker/login-action@v4
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}


            - name: build and push
              uses: docker/build-push-action@v7
              with:
                context: .
                file: docker/Dockerfile
                push: true
                tags: mdfaiz01/sample-image:latest
                
