name: python app test
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: check out the repo
              uses: actions/checkout@v7
            
            - name: listing the available files
              run: ls -al

            - name: install the packages
              run: pip install -r cal-app/requirements.txt

            - name: testing the app
              run: pytest cal-app/test_calculator.py

            - name: exporting the results
              run: pytest cal-app/test_calculator.py > results.txt

            - name: upload
              uses: actions/upload-artifact@v7
              with:
                name: test-result
                path: results.txt
              

